var gameData = {
  game: [
    {
      id: "0001",
      date: "9/01",
      time: "9:30 AM",
      location: "AJKatzenmaier",
      teams: ["U1", "U4"],
    },
    {
      id: "0002",
      date: "9/01",
      time: "1:00 PM",
      location: "Greenbay",
      teams: ["U3", "U2"],
    },
    {
      id: "0003",
      date: "9/08",
      time: "9:30 AM",
      location: "Greenbay",
      teams: ["U3", "U2"],
    },
    {
      id: "0004",
      date: "9/08",
      time: "1:00 PM",
      location: "MarjoriePHart",
      teams: ["U6", "U1"],
    },
    {
      id: "0005",
      date: "9/15",
      time: "9:30 AM",
      location: "North",
      teams: ["U2", "U4"],
    },
    {
      id: "0006",
      date: "9/15",
      time: "1:00 PM",
      location: "AJKatzenmaier",
      teams: ["U3", "U5"],
    },
    {
      id: "0007",
      date: "9/22",
      time: "9:30 PM",
      location: "South",
      teams: ["U1", "U3"],
    },
    {
      id: "0008",
      date: "9/22",
      time: "1:00 PM",
      location: "HowardAYeager",
      teams: ["U2", "U6"],
    },
    {
      id: "0009",
      date: "9/29",
      time: "9:30 AM",
      location: "Greenbay",
      teams: ["U4", "U5"],
    },
    {
      id: "0010",
      date: "10/06",
      time: "9:30 AM",
      location: "MarjoriePHart",
      teams: ["U2", "U5"],
    },
    {
      id: "0011",
      date: "10/06",
      time: "1:00 PM",
      location: "South",
      teams: ["U1", "U6"],
    },
    {
      id: "0012",
      date: "10/13",
      time: "9:30 AM",
      location: "HowardAYeager",
      teams: ["U5", "U1"],
    },
    {
      id: "0013",
      date: "10/13",
      time: "1:00 PM",
      location: "Greenbay",
      teams: ["U5", "U1"],
    },
    {
      id: "0014",
      date: "10/20",
      time: "9:30 AM",
      location: "North",
      teams: ["U6", "U3"],
    },
    {
      id: "0015",
      date: "10/20",
      time: "1:00 PM",
      location: "MarjoriePHart",
      teams: ["U2", "U4"],
    },
    {
      id: "0016",
      date: "10/27",
      time: "9:30 AM",
      location: "AJKatzenmaier",
      teams: ["U3", "U1"],
    },
    {
      id: "0017",
      date: "10/27",
      time: "9:30 AM",
      location: "HowardAYeager",
      teams: ["U5", "U6"],
    },
  ],
};
